name: MxMoney

options:
  bundleIdPrefix: com.urielh
  xcodeVersion: 14
  deploymentTarget:
    iOS: "16.0"
  useTabs: false
  # When using pods
  postGenCommand: pod install
  
settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5P4JJDT7CR
    MARKETING_VERSION: "1.0"
    BUNDLE_VERSION: "1"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
  
targets:
  MxMoney:
    platform: iOS
    type: application
    sources:
      - MxMoney
    scheme:
      testTargets:
        - MxMoneyTests
      gatherCoverageData: true
      coverageTargets:
        - MxMoney
    postCompileScripts:
      - script: |
          export PATH="$PATH:/opt/homebrew/bin"

          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi

        name: Swiftlint
  MxMoneyTests:
    platform: iOS
    type: bundle.unit-test
    dependencies:
      - target: MxMoney
    sources:
      MxMoneyTests
    info:
      path: Info.plist
